version: '3'

services:
  app:
    build: .
    command: inv
    restart: always
    volumes:
      - ./invoke.yaml:/app/invoke.yaml

  api:
    build: .
    command: api
    restart: always
    volumes:
      - ./model.json:/app/model.json